# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
