# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20161204_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.CharField(default='\n\tCheckout this awesome video.\n', max_length=333),
        ),
    ]
